/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)reda_dbShell.h    generated by: makeheader    Fri Apr 23 00:10:54 2021
 *
 *		built from:	dbShell.ifc
 */

#ifndef reda_dbShell_h
#define reda_dbShell_h


  #ifndef reda_database_h
    #include "reda/reda_database.h"
  #endif
  #ifndef reda_worker_h
    #include "reda/reda_worker.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

extern REDADllExport void REDADBShell_run(struct REDADatabase* database,
					  struct REDAWorker* worker);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* reda_dbShell_h */
