/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_buildid.h    generated by: makeheader    Fri Apr 23 00:38:50 2021
 *
 *		built from:	buildid.ifc
 */

#ifndef dds_cpp_buildid_h
#define dds_cpp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCPP_BUILD_6.1.0_20210422T111111Z_RTI_REL"
#endif

#endif /* dds_cpp_buildid_h */
