/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_tls_log.h    generated by: makeheader    Fri Nov 15 12:23:54 2019
 *
 *		built from:	log.ifc
 */

#ifndef transport_tls_log_h
#define transport_tls_log_h


  #ifndef log_common_h
    #include "log/log_common.h"
  #endif
  #ifndef transport_tls_dll_h
    #include "transport_tls/transport_tls_dll.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif


/*i \ingroup NDDS_TransportTLSLogMessageClass
  \brief Transport-TLS OpenSSL identifier. For use in log message numbers.
  @see RTILogNumberBitmapClass
 */
  #define SUBMODULE_TRANSPORT_TLS_OPENSSL          (0x0000)

/*i \ingroup NDDS_TransportTLSLogMessageClass
  \brief Transport-TLS DTLS identifier. For use in log message numbers.
  @see RTILogNumberBitmapClass
 */
  #define SUBMODULE_TRANSPORT_TLS_DTLS             (0x0001)

/*i \ingroup NDDS_TransportTLSLogMessageClass
  \brief Transport-TLS plugin identifier. For use in log message numbers.
  @see RTILogNumberBitmapClass
 */
  #define SUBMODULE_TRANSPORT_TLS_PLUGIN           (0x0002)

/*i \ingroup NDDS_TransportTLSLogMessageClass
  \brief Transport-TLS/WAN plugin identifier. For use in log message numbers.
  @see RTILogNumberBitmapClass
 */
  #define SUBMODULE_TRANSPORT_TLS_PLUGIN_WAN       (0x0003)



  #define NDDS_TRANSPORT_TLS_SUBMODULE_MASK_OPENSSL (0x0001)


  #define NDDS_TRANSPORT_TLS_SUBMODULE_MASK_DTLS  (0x0002)


  #define NDDS_TRANSPORT_TLS_SUBMODULE_MASK_PLUGIN  (0x0004)


  #define NDDS_TRANSPORT_TLS_SUBMODULE_MASK_PLUGIN_WAN (0x0008)


  #define NDDS_TRANSPORT_TLS_SUBMODULE_MASK_ALL     (0xFFFF)

extern NDDS_Transport_TLS_DllVariable const struct RTILogMessage NDDS_TRANSPORT_TLS_LOG_OPENSSL_VERIFICATION_FAILURE_dds;

extern NDDS_Transport_TLS_DllVariable const struct RTILogMessage NDDS_TRANSPORT_TLS_LOG_OPENSSL_VERIFICATION_SUCCESS;

extern NDDS_Transport_TLS_DllVariable const struct RTILogMessage NDDS_TRANSPORT_TLS_LOG_OPENSSL_VERIFICATION_CERTINFO_ss;

extern NDDS_Transport_TLS_DllExport void NDDS_Transport_TLS_Log_set_verbosity(
    RTILogBitmap submoduleMask, int verbosity);

extern NDDS_Transport_TLS_DllExport void NDDS_Transport_TLS_Log_set_security_verbosity(
    RTILogBitmap submoduleMask, int verbosity);

extern NDDS_Transport_TLS_DllExport void NDDS_Transport_TLS_Log_setBitmaps(
    RTILogBitmap submoduleMask, RTILogBitmap instrumentationMask);

extern NDDS_Transport_TLS_DllExport void NDDS_Transport_TLS_Log_getBitmaps(
    RTILogBitmap *submoduleMask, RTILogBitmap *instrumentationMask);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* transport_tls_log_h */
