/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_dynamicdata_jsonparser.h    generated by: makeheader    Fri Apr 23 00:05:59 2021
 *
 *		built from:	dynamicdata_jsonparser.ifc
 */

#ifndef dds_c_dynamicdata_jsonparser_h
#define dds_c_dynamicdata_jsonparser_h


#ifndef dds_c_dynamicdata_h
  #include "dds_c/dds_c_dynamicdata.h"
#endif

#ifndef osapi_utility_h
  #include "osapi/osapi_utility.h"
#endif

#ifdef __cplusplus
  extern "C" {
#endif


struct DDS_DynamicDataJsonParserProperties_t {
    struct DDS_DynamicDataProperty_t object_property;
    struct DDS_DynamicDataProperty_t array_property;
};

 extern DDSCDllVariable struct DDS_DynamicDataJsonParserProperties_t
        DDS_DYNAMIC_DATA_JSON_PARSER_PROPERTIES_DEFAULT;


#define DDS_DynamicDataJsonParserProperties_t_INITIALIZER { \
    DDS_DynamicDataProperty_t_INITIALIZER, /* object_property */ \
    DDS_DynamicDataProperty_t_INITIALIZER /* array_property */ \
}


#ifdef __cplusplus
    }   /* extern "C" */
#endif

#endif /* dds_c_dynamicdata_jsonparser_h */
