/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)connext_cpp_buildid.h    generated by: makeheader    Fri Apr 23 01:37:17 2021
 *
 *		built from:	buildid.ifcxx
 */

#ifndef connext_cpp_buildid_h
#define connext_cpp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "CONNEXTMSGCPP_BUILD_6.1.0_20210422T111111Z_RTI_REL"
#endif

#endif /* connext_cpp_buildid_h */
