/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)osapi_platform.h    generated by: makeheader    Fri Apr 23 00:09:55 2021
 *
 *		built from:	platform.ifc
 */

#ifndef osapi_platform_h
#define osapi_platform_h


/*
 * ENABLE_FACE_COMPLIANCE: These match the definitions in Micro
 * 0 - No compliance with FACE is required
 * 1 - Comply with the SECURITY profile (not supported)
 * 2 - Comply with the SAFETY_BASE profile (not supported)
 * 3 - Comply with the SAFETY_EXTENDED profile (not supported)
 * 4 - Comply with the GENERAL profile (supported)
 */
#ifndef FACE_COMPLIANCE_LEVEL_NONE
#define FACE_COMPLIANCE_LEVEL_NONE             0
#endif
#ifndef FACE_COMPLIANCE_LEVEL_SECURITY
#define FACE_COMPLIANCE_LEVEL_SECURITY         1
#endif
#ifndef FACE_COMPLIANCE_LEVEL_SAFETY_BASE
#define FACE_COMPLIANCE_LEVEL_SAFETY_BASE      2
#endif
#ifndef FACE_COMPLIANCE_LEVEL_SAFETY_EXTENDED
#define FACE_COMPLIANCE_LEVEL_SAFETY_EXTENDED  3
#endif
#ifndef FACE_COMPLIANCE_LEVEL_GENERAL
#define FACE_COMPLIANCE_LEVEL_GENERAL          4
#endif

#ifndef ENABLE_FACE_COMPLIANCE
#define ENABLE_FACE_COMPLIANCE                   FACE_COMPLIANCE_LEVEL_NONE
#endif

#if (ENABLE_FACE_COMPLIANCE != FACE_COMPLIANCE_LEVEL_NONE)
  #if (ENABLE_FACE_COMPLIANCE != FACE_COMPLIANCE_LEVEL_GENERAL)
  #error "RTI Connext DDS only supports FACE GENERAL profile"
  #endif
#endif


#endif /* osapi_platform_h */
