/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)osapi_rtpsGuid.h    generated by: makeheader    Fri Apr 23 00:09:56 2021
 *
 *		built from:	rtpsGuid.ifc
 */

#ifndef osapi_rtpsGuid_h
#define osapi_rtpsGuid_h



  #ifndef osapi_dll_h
    #include "osapi/osapi_dll.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif


struct RTIOsapiRtpsGuidPrefix {
    RTI_UINT32 hostId;
    RTI_UINT32 appId;
    RTI_UINT32 instanceId;
};


  #define RTI_OSAPI_RTPS_GUID_PREFIX_UNKNOWN { \
    0, \
    0, \
    0}


struct RTIOsapiRtpsGuid {
    struct RTIOsapiRtpsGuidPrefix prefix;
    RTI_UINT32 objectId;
};


  #define RTI_OSAPI_RTPS_GUID_UNKNOWN { \
    RTI_OSAPI_RTPS_GUID_PREFIX_UNKNOWN, \
    0}

extern RTIOsapiDllExport
RTIBool RTIOsapiRtpsGuidPrefix_equals(
        const struct RTIOsapiRtpsGuidPrefix *a,
        const struct RTIOsapiRtpsGuidPrefix *b);

extern RTIOsapiDllExport
RTIBool RTIOsapiRtpsGuid_equals(
        const struct RTIOsapiRtpsGuid *a,
        const struct RTIOsapiRtpsGuid *b);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#include "osapi/osapi_rtpsGuid_impl.h"

#endif /* osapi_rtpsGuid_h */
