/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)connext_c_buildid.h    generated by: makeheader    Fri Apr 23 00:52:52 2021
 *
 *		built from:	buildid.ifc
 */

#ifndef connext_c_buildid_h
#define connext_c_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "CONNEXTMSGC_BUILD_6.1.0_20210422T111111Z_RTI_REL"
#endif

#endif /* connext_c_buildid_h */
