/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_buildid.h    generated by: makeheader    Fri Nov 15 12:23:00 2019
 *
 *		built from:	buildid.ifcxx
 */

#ifndef dds_cpp_buildid_h
#define dds_cpp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCPP_BUILD_6.0.1.0_20191115T195316Z_RTI_REL"
#endif

#endif /* dds_cpp_buildid_h */
