/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_data_TDataWriter.h    generated by: makeheader    Fri Apr 23 00:09:48 2021
 *
 *		built from:	dds_c_data_TDataWriter.gen
 */

#ifndef dds_c_data_TDataWriter_h
#define dds_c_data_TDataWriter_h

#ifdef __cplusplus
    extern "C" {
#endif

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_data_TDataWriter_h */
