/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_tls_buildid.h    generated by: makeheader    Fri Apr 23 02:31:08 2021
 *
 *		built from:	buildid.ifc
 */

#ifndef transport_tls_buildid_h
#define transport_tls_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTITRANSPORTTLS_BUILD_6.1.0_20210422T111111Z_RTI_REL"
#endif

#endif /* transport_tls_buildid_h */
