/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_tls_plugin_impl.h    generated by: makeheader    Fri Apr 23 02:31:08 2021
 *
 *		built from:	plugin_impl.ifc
 */

#ifndef transport_tls_plugin_impl_h
#define transport_tls_plugin_impl_h


#ifdef __cplusplus
    extern "C" {
#endif


struct NDDS_Transport_DTLS {
    NDDS_Transport_Plugin                       parent;
    struct NDDS_Transport_DTLS_Property_t      _property;

    /* for built-in performance measurement */
    struct RTIClock                   *_clock; 

    /* low-level transport */
    struct NDDS_Transport_UDPv4               *_baseTransport;
    /* gather send before TLS encode (per base send resource?) */
    struct NDDS_Transport_DTLS_gatherSendBuffer* _gatherSendBuffer;

    /* use DTLS module to implement TLS connections */
    struct NDDS_Transport_DTLS_Connection_Mapper* _connectionMapper;
};


#define NDDS_Transport_DTLS_new(property_in) \
        NDDS_Transport_DTLS_newI(property_in, NULL, NULL)


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* transport_tls_plugin_impl_h */
