/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)advlog_context_impl.h    generated by: makeheader    Fri Apr 23 00:04:25 2021
 *
 *		built from:	context_impl.ifc
 */

#ifndef advlog_context_impl_h
#define advlog_context_impl_h


#ifdef __cplusplus
    extern "C" {
#endif


#define ADVLOGContextScope_beginWithEntries(maxEntryCount) \
    RTIOsapiActivityContextScope_beginWithEntries(maxEntryCount)

#define ADVLOGContextScope_beginWithEntriesAndParams( \
        maxEntryCount, \
        maxParamsCount) \
    RTIOsapiActivityContextScope_beginWithEntriesAndParams( \
            (maxEntryCount), \
            (maxParamsCount))

#define ADVLOGContextScope_enterActivity(contextTemplate) \
    RTIOsapiActivityContextScope_enterActivity( \
            (contextTemplate)->format)

#define ADVLOGContextScope_enterActivityWithParams(contextTemplate, ...) \
    RTIOsapiActivityContextScope_enterActivityWithParams( \
            (contextTemplate)->format, \
            __VA_ARGS__)

#define ADVLOGContextScope_enterResource(resource) \
    RTIOsapiActivityContextScope_enterResource( \
            RTI_ADVLOG_CONTEXT_TEMPLATE_RESOURCE_s.format, \
            (resource))

#define ADVLOGContextScope_enterResourceWithParams( \
        contextTemplate, \
        ...) \
    RTIOsapiActivityContextScope_enterResourceWithParams( \
            (contextTemplate)->format, \
            __VA_ARGS__)

#define ADVLOGContextScope_enterResourceGuidWithParams( \
        contextTemplate, \
        ...) \
    RTIOsapiActivityContextScope_enterResourceGuidWithParams( \
            (contextTemplate)->format, \
            __VA_ARGS__)

#define ADVLOGContextScope_end() \
    RTIOsapiActivityContextScope_end()


#define ADVLOGContext_enter(entry) \
    RTIOsapiActivityContext_enter(entry)

#define ADVLOGContext_enterPair(self, entry1, entry2) \
    RTIOsapiActivityContext_enterPair((self), (entry1), (entry2))

#define ADVLOGContext_enterGroup(groupSize, ...) \
    RTIOsapiActivityContext_enterGroup((groupSize), __VA_ARGS__)

#define ADVLOGContextScope_leave() \
    RTIOsapiActivityContextScope_leave()

#define ADVLOGContext_leave() \
    RTIOsapiActivityContext_leave()

#define ADVLOGContext_leaveGroup(self, groupSize) \
    RTIOsapiActivityContext_leaveGroup((self), (groupSize))



#ifdef __cplusplus
    }	/* extern "C" */
#endif


#endif /* advlog_context_impl_h */
