/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)routingservice_processor_impl.h    generated by: makeheader    Fri Apr 23 01:06:17 2021
 *
 *		built from:	processor_impl.ifc
 */

#ifndef routingservice_processor_impl_h
#define routingservice_processor_impl_h


  #ifndef router_dll_h
    #include "routingservice/routingservice_dll.h"
  #endif
  #include "routingservice/routingservice_processor.h"
  #ifdef __cplusplus
      extern "C" {
  #endif

extern ROUTERDllExport
struct RTI_RoutingServiceStreamRequest *
RTI_RoutingServiceInput_create_stream_request(
        RTI_RoutingServiceInput *self,
        struct RTI_RoutingServiceStreamRequest *stream_request,
        const RTI_RoutingServiceSampleInfo *stream_request_info);

extern ROUTERDllExport
DDS_Boolean RTI_RoutingServiceInput_delete_stream_request(
        RTI_RoutingServiceInput *self,
        int service_id,
        const struct RTI_RoutingServiceGuid *request_guid);

extern ROUTERDllExport
struct RTI_RoutingServiceConnectionExt *
RTI_RoutingServiceInput_get_connection(
        RTI_RoutingServiceInput *self);

extern ROUTERDllExport
struct RTI_RoutingServiceStreamReaderExt *
RTI_RoutingServiceInput_get_stream_reader(
        RTI_RoutingServiceInput *self);

extern ROUTERDllExport
void RTI_RoutingServiceInput_set_user_data(
        RTI_RoutingServiceInput *self,
        void *userData);

extern ROUTERDllExport
void * RTI_RoutingServiceInput_get_user_data(
        RTI_RoutingServiceInput *self);

extern ROUTERDllExport
DDS_DataReader * RTI_RoutingServiceInput_get_dds_reader(
        RTI_RoutingServiceInput *input);

extern ROUTERDllExport
void RTI_RoutingServiceInput_notify_stream_reader_listener(
        RTI_RoutingServiceInput *self);

extern ROUTERDllExport
struct RTI_RoutingServiceConnectionExt *
RTI_RoutingServiceOutput_get_connection(
        RTI_RoutingServiceOutput *self);

extern ROUTERDllExport
DDS_Boolean RTI_RoutingServiceOutput_write_w_params(
        RTI_RoutingServiceOutput *self,
        RTI_RoutingServiceSample sample,
        struct RTI_RoutingServiceWriteParams *params);

extern ROUTERDllExport
struct RTI_RoutingServiceStreamWriterExt *
RTI_RoutingServiceOutput_get_stream_writer(
        RTI_RoutingServiceOutput *self);

extern ROUTERDllExport
void RTI_RoutingServiceOutput_set_user_data(
        RTI_RoutingServiceOutput *self,
        void *userData);

extern ROUTERDllExport
void * RTI_RoutingServiceOutput_get_user_data(
        RTI_RoutingServiceOutput *self);

extern ROUTERDllExport
DDS_DataWriter * RTI_RoutingServiceOutput_get_dds_writer(
         RTI_RoutingServiceOutput *output);


struct RTI_RoutingServiceRouteEventImpl {
    RTI_RoutingServiceRouteEventKind eventKind;
    RTI_RoutingServiceRoute *route;
    void *affectedEntity;
    void *eventData;
};

extern ROUTERDllExport
const char *
RTI_RoutingServiceRouteEventKind_to_string(
        RTI_RoutingServiceRouteEventKind kind);

extern ROUTERDllExport
void RTI_RoutingServiceOutputStreamRequestStatus_finalize(
        void * eventData);

extern ROUTERDllExport
void RTI_RoutingServiceOutputStreamRequestStatus_initialize(
        void * eventData);

extern ROUTERDllExport
void * RTI_RoutingServiceOutputStreamRequestStatus_copy(
        void * dest,
        const void * src);


  #ifdef __cplusplus
    }	/* extern "C" */
  #endif

#endif /* routingservice_processor_impl_h */
