/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)routingservice_buildid.h    generated by: makeheader    Fri Apr 23 01:06:19 2021
 *
 *		built from:	buildid.ifc
 */

#ifndef routingservice_buildid_h
#define routingservice_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "ROUTER_BUILD_6.1.0_20210422T111111Z_RTI_REL"
#endif

#endif /* routingservice_buildid_h */
