/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_wan_version.h    generated by: makeheader    Fri Apr 23 02:31:41 2021
 *
 *		built from:	version.ifc
 */

#ifndef transport_wan_version_h
#define transport_wan_version_h

 
#ifndef log_makeheader_h
  #include "log/log_makeheader.h"
#endif
#ifndef transport_wan_dll_h
  #include "transport_wan/transport_wan_dll.h"
#endif
#ifndef dds_c_infrastructure_h 
  #include "dds_c/dds_c_infrastructure.h"
#endif
  
#ifdef __cplusplus
extern "C" {
#endif


typedef struct DDS_ProductVersion_t NDDS_Transport_WAN_LibraryVersion;

extern NDDS_Transport_WAN_DllExport
const NDDS_Transport_WAN_LibraryVersion *
        NDDS_Transport_WAN_get_library_version();

extern NDDS_Transport_WAN_DllExport
const char *NDDS_Transport_WAN_get_build_version_string();


#ifdef __cplusplus
}       /* extern "C" */
#endif

#endif /* transport_wan_version_h */
