/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)persistence_buildid.h    generated by: makeheader    Fri Nov 15 12:24:16 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef persistence_buildid_h
#define persistence_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "PERSISTENCESERVICE_BUILD_6.0.1.0_20191115T195316Z_RTI_REL"
#endif

#endif /* persistence_buildid_h */
