/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)rtixml_infrastructure_impl.h    generated by: makeheader    Fri Apr 23 00:11:21 2021
 *
 *		built from:	infrastructure_impl.ifc
 */

#ifndef rtixml_infrastructure_impl_h
#define rtixml_infrastructure_impl_h



#ifndef rtixml_infrastructure_h
  #include "rtixml/rtixml_infrastructure.h"
#endif

  #ifdef __cplusplus
      extern "C" {
  #endif




struct RTIXMLPropertyList {
    struct RTIXMLProperty *_array;
    RTI_UINT32 _arrayLength;
};


  #ifdef __cplusplus
    }	/* extern "C" */
  #endif

#endif /* rtixml_infrastructure_impl_h */
