/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)rti_dl_buildid_cpp.h    generated by: makeheader    Fri Nov 15 12:23:45 2019
 *
 *		built from:	buildid_cpp.ifc
 */

#ifndef rti_dl_buildid_cpp_h
#define rti_dl_buildid_cpp_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTIDISTRIBUTEDLOGCPP_BUILD_6.0.1.0_20191115T195316Z_RTI_REL"
#endif

#endif /* rti_dl_buildid_cpp_h */
