/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_data_TDataReader.h    generated by: makeheader    Fri Nov 15 12:23:00 2019
 *
 *		built from:	TDataReader.cxx
 */

#ifndef dds_cpp_data_TDataReader_h
#define dds_cpp_data_TDataReader_h

#endif /* dds_cpp_data_TDataReader_h */
