/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_data_TDataWriter.h    generated by: makeheader    Fri Nov 15 12:23:00 2019
 *
 *		built from:	TDataWriter.cxx
 */

#ifndef dds_cpp_data_TDataWriter_h
#define dds_cpp_data_TDataWriter_h

#endif /* dds_cpp_data_TDataWriter_h */
