/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)recordingservice_dll.h    generated by: makeheader    Fri Apr 23 01:05:41 2021
 *
 *		built from:	dll.ifc
 */

#ifndef recordingservice_dll_h
#define recordingservice_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE) || defined(RTI_INTIME)
  #if defined(RTI_recordingservice_DLL_EXPORT)
    #define RECORDERDllExport __declspec( dllexport )
  #else
    #define RECORDERDllExport
  #endif /* RTI_recordingservice_DLL_EXPORT */

  #if defined(RTI_recordingservice_DLL_VARIABLE) 
    #if defined(RTI_recordingservice_DLL_EXPORT)
      #define RECORDERDllVariable __declspec( dllexport )
    #else
      #define RECORDERDllVariable __declspec( dllimport )
    #endif /* RTI_recordingservice_DLL_EXPORT */
  #else 
    #define RECORDERDllVariable
  #endif /* RTI_recordingservice_DLL_VARIABLE */
#else
  #define RECORDERDllExport
  #define RECORDERDllVariable
#endif /* RTI_WIN32 || RTI_WINCE || RTI_INTIME */


#endif /* recordingservice_dll_h */
