/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dl_driver_odbcSetup.h    generated by: makeheader    Fri Apr 23 00:06:22 2021
 *
 *		built from:	odbcSetup.ifc
 */

#ifndef dl_driver_odbcSetup_h
#define dl_driver_odbcSetup_h



#include "osapi/osapi_type.h"
#include "dl_driver/dl_driver_dll.h"

#if defined(RTI_WIN32) || defined(RTI_WINCE)
#include <windows.h>
#endif



#define DLDRIVER_ODBC_PLUGIN_DSN_MAX_LENGTH 512
#define DLDRIVER_ODBC_PLUGIN_LIBNAME_MAX_LENGTH 255


struct DLDRIVERTestOdbcDatabaseInfo {
    char DSN[DLDRIVER_ODBC_PLUGIN_DSN_MAX_LENGTH];
    char odbcDatabaseLib[DLDRIVER_ODBC_PLUGIN_LIBNAME_MAX_LENGTH];
};


#define DLDRIVER_TEST_ODBC_DATABASE_INFO_DEFAULT { \
    "", /* DSN */ \
    "", /* odbcDatabaseLib */ \
}

extern DLDRIVERDllExport
RTIBool DLDRIVERTestOdbcDatabaseInfo_populate(
        struct DLDRIVERTestOdbcDatabaseInfo *self,
        const char *dsn,
        const char *odbcDatabaseLib);

extern DLDRIVERDllExport
RTIBool DLDRIVEROdbcSetup_testSetup(
        const char *user,
        const char *odbcIniPath,
        const char *database,
        const struct DLDRIVERTestOdbcDatabaseInfo *mysqlOdbcDatabaseInfo);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dl_driver_odbcSetup_h */
