/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)monitor_buildid.h    generated by: makeheader    Fri Nov 15 12:23:52 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef monitor_buildid_h
#define monitor_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTIMONITORING_BUILD_6.0.1.0_20191115T195316Z_RTI_REL"
#endif

#endif /* monitor_buildid_h */
