/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)core_version_version.h    generated by: makeheader    Fri Apr 23 00:05:15 2021
 *
 *		built from:	version.ifc
 */

#ifndef core_version_version_h
#define core_version_version_h


  #ifndef rtilib_endian_h
    #include "osapi/osapi_type.h"
  #endif
  #ifndef core_version_dll_h
    #include "core_version/core_version_dll.h"
  #endif
  #ifndef core_version_version_impl_h
    #include "core_version/core_version_version_impl.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif


#ifndef RTI_DOOZER_BUILD
#ifndef RTI_NDDS_VERSION_MAJOR
#define RTI_NDDS_VERSION_MAJOR 6
#endif
#ifndef RTI_NDDS_VERSION_MINOR
#define RTI_NDDS_VERSION_MINOR 0
#endif
#ifndef RTI_NDDS_VERSION_RELEASE
#define RTI_NDDS_VERSION_RELEASE 0
#endif
#ifndef RTI_NDDS_VERSION_REVISION
#define RTI_NDDS_VERSION_REVISION 0
#endif
#endif

struct VERSLibraryVersion {
    /*e @brief  The major release version number. */
    RTI_INT32 majorVersion;

    /*e @brief  The minor release version number. */
    RTI_INT32 minorVersion;

    /*e @brief  The release version number. */
    RTI_INT32 releaseVersion;

    /*e @brief  The revision number. */
    RTI_INT32 revisionVersion;
};

extern VERSDllExport
const struct VERSLibraryVersion * VERSLibraryVersion_getCoreVersion(void);

extern VERSDllExport
const char* VERSLibraryVersion_coreVersionToString(void);

extern VERSDllExport
const char * VERSLibraryVersion_getBuildNumberString(void);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* core_version_version_h */
