/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_wan_buildid.h    generated by: makeheader    Fri Nov 15 12:24:00 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef transport_wan_buildid_h
#define transport_wan_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTITRANSPORTWAN_BUILD_6.0.1.0_20191115T195316Z_RTI_REL"
#endif

#endif /* transport_wan_buildid_h */
