/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_wan_dll.h    generated by: makeheader    Fri Nov 15 12:24:00 2019
 *
 *		built from:	dll.ifc
 */

#ifndef transport_wan_dll_h
#define transport_wan_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE)
  #if defined(RTI_transport_wan_DLL_EXPORT)
    #define NDDS_Transport_WAN_DllExport __declspec( dllexport )
  #else
    #define NDDS_Transport_WAN_DllExport
  #endif /* NDDS_transport_DLL_EXPORT */

  #if defined(RTI_transport_wan_DLL_VARIABLE) 
    #if defined(RTI_transport_wan_DLL_EXPORT)
      #define NDDS_Transport_WAN_DllVariable __declspec( dllexport )
    #else
      #define NDDS_Transport_WAN_DllVariable __declspec( dllimport )
    #endif /* NDDS_transport_DLL_EXPORT */
  #else 
    #define NDDS_Transport_WAN_DllVariable
    #endif /* NDDS_transport_DLL_VARIABLE */
#else
  #define NDDS_Transport_WAN_DllExport
  #define NDDS_Transport_WAN_DllVariable
#endif /* RTI_WIN32 || RTI_WINCE */

#endif /* transport_wan_dll_h */
