/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)metp_buildid.h    generated by: makeheader    Fri Nov 15 12:23:11 2019
 *
 *		built from:	buildid.ifc
 */

#ifndef metp_buildid_h
#define metp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "METPC_BUILD_6.0.1.0_20191115T195316Z_RTI_REL"
#endif

#endif /* metp_buildid_h */
