/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_data_TDataWriter.h    generated by: makeheader    Fri Apr 23 00:39:32 2021
 *
 *		built from:	dds_cpp_data_TDataWriter.gen
 */

#ifndef dds_cpp_data_TDataWriter_h
#define dds_cpp_data_TDataWriter_h

#endif /* dds_cpp_data_TDataWriter_h */
