/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_data_TDataReader.h    generated by: makeheader    Fri Apr 23 00:39:31 2021
 *
 *		built from:	dds_cpp_data_TDataReader.gen
 */

#ifndef dds_cpp_data_TDataReader_h
#define dds_cpp_data_TDataReader_h

#endif /* dds_cpp_data_TDataReader_h */
