/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)ndds_version.h    generated by: makeheader    Fri Apr 23 00:06:21 2021
 *
 *		built from:	ndds_version.ifc
 */

#ifndef ndds_version_h
#define ndds_version_h


#define RTI_DDS_VERSION_MAJOR    6
#define RTI_DDS_VERSION_MINOR    1
#define RTI_DDS_VERSION_RELEASE  0
#define RTI_DDS_VERSION_REVISION 0

#endif /* ndds_version_h */
