/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)ndds_version.h    generated by: makeheader    Fri Nov 15 12:22:54 2019
 *
 *		built from:	ndds_version.ifc
 */

#ifndef ndds_version_h
#define ndds_version_h


#define RTI_DDS_VERSION_MAJOR  6
#define RTI_DDS_VERSION_MINOR  0
#define RTI_DDS_VERSION_RELEASE 1
#define RTI_DDS_VERSION_REVISION 0

#endif /* ndds_version_h */
