/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)ndds_transport_tcp.h    generated by: makeheader    Fri Nov 15 12:25:19 2019
 *
 *		built from:	transport_tcp.ifc
 */

#ifndef ndds_transport_tcp_h
#define ndds_transport_tcp_h



  #ifdef NDDS_TRANSPORT_TCP_DLL_VARIABLE
    #define RTI_transport_tcp_DLL_VARIABLE
  #endif

  #ifndef transport_tcp_tcpv4_h
    #include "ndds/transport_tcp/transport_tcp_tcpv4.h"
  #endif


#endif /* ndds_transport_tcp_h */
