/* (c) Copyright 2003-2019, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)osapi_interfaceTracker_impl.h    generated by: makeheader    Fri Nov 15 12:21:39 2019
 *
 *		built from:	interfaceTracker_impl.ifc
 */

#ifndef osapi_interfaceTracker_impl_h
#define osapi_interfaceTracker_impl_h


#ifdef __cplusplus
    extern "C" {
#endif


struct RTIOsapiInterfaceTracker;

extern RTIOsapiDllExport
RTIBool RTIOsapiInterfaceTracker_isPollingEnabled(
        const struct RTIOsapiInterfaceTracker *interfaceTracker);


#ifdef __cplusplus
    }   /* extern "C" */
#endif

#endif /* osapi_interfaceTracker_impl_h */
